### ISSUE TITLE
Not compatible with Sails v.10.x

### ISSUE THREAD

**Issue by r0hitsharma** [murilopolese/sails-parse#1]
Guess the adapters have changed with the version update.

> warn: The adapter `sails-parse` appears to be designed for an earlier version of Sails.
> warn: (it has a `registerCollection()` method.)
> warn: Since you're running Sails v0.10.x, it probably isn't going to work.
> warn: To attempt to install the updated version of this adapter, run:
> warn: npm install sails-parse@0.10.x
> error: There was an error attempting to require("sails-parse")
> error: Is this a valid Sails/Waterline adapter?  The following error was encountered ::
> error: Adapter is not compatible with the current version of Sails.

**Comment by tskaggs** [comment]
Any progress made on this?

Edit: I started building the 0.10.x version. It's at the beginning stages but any contribution would be awesome. https://github.com/tskaggs/sails-parse/tree/v0.10.x

**Comment by murilopolese** [comment]
Hey! Sorry for the late answer... I will have a look on this asap :)

**Comment by tskaggs** [comment]
@murilopolese Cool! Checkout https://github.com/tskaggs/sails-parse/. Test still have issues with destroy and other things but it's a start.
